.TH "lib Directory Reference" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBformats\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBenchmark\&.cc\fP"
.br
.ti -1c
.RI "file \fBCMS\&.cc\fP"
.br
.ti -1c
.RI "file \fBCropSolution\&.cc\fP"
.br
.ti -1c
.RI "file \fBDestination\&.cc\fP"
.br
.ti -1c
.RI "file \fBDestination_items\&.cc\fP"
.br
.ti -1c
.RI "file \fBDitherer\&.cc\fP"
.br
.ti -1c
.RI "file \fBFrame\&.cc\fP"
.br
.ti -1c
.RI "file \fBImage\&.cc\fP"
.br
.ti -1c
.RI "file \fBImageFile\&.cc\fP"
.br
.ti -1c
.RI "file \fBKernel1Dvar\&.cc\fP"
.br
.ti -1c
.RI "file \fBKernel2D\&.cc\fP"
.br
.ti -1c
.RI "file \fBLCMS2ErrorHandler\&.cc\fP"
.br
.ti -1c
.RI "file \fBTags\&.cc\fP"
.br
.ti -1c
.RI "file \fBTags_EXIF_subst\&.cc\fP"
.br
.ti -1c
.RI "file \fBTags_IPTC_subst\&.cc\fP"
.br
.ti -1c
.RI "file \fBTags_XMP_subst\&.cc\fP"
.br
.in -1c
