.TH "Definable.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Definable.hh
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhotoFinish::definable< T >\fP"
.br
.RI "Template class for storing things that can be defined or undefined\&. "
.ti -1c
.RI "class \fBPhotoFinish::Role_Definable\fP"
.br
.RI "Base class for adding 'definable' attribute\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
