.TH "Destination.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Destination.hh
.SH SYNOPSIS
.br
.PP
\fC#include 'yaml\-cpp/yaml\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include 'CMS\&.hh'\fP
.br
\fC#include 'Destination_items\&.hh'\fP
.br
\fC#include 'Image\&.hh'\fP
.br
\fC#include 'Frame\&.hh'\fP
.br
\fC#include 'Definable\&.hh'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhotoFinish::Destination\fP"
.br
.RI "Represents a destination, read from destinations\&.yml\&. "
.ti -1c
.RI "class \fBPhotoFinish::Destinations\fP"
.br
.RI "A wrapper class for reading destinations from a YAML file and storing them in a map\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
