.TH "Ditherer.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ditherer.hh
.SH SYNOPSIS
.br
.PP
\fC#include <lcms2\&.h>\fP
.br
\fC#include 'sample\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhotoFinish::Ditherer\fP"
.br
.RI "Class for dithering images down to 8-bit components\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
