.TH "Exception.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exception.hh
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhotoFinish::Uninitialised\fP"
.br
.RI "\fBUninitialised\fP attribute exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::Unimplemented\fP"
.br
.RI "\fBUnimplemented\fP method exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::NoResults\fP"
.br
.RI "No results exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::NoTargets\fP"
.br
.RI "No targets exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::ErrorMsg\fP"
.br
.RI "Generic error message exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::MemAllocError\fP"
.br
.RI "Memory allocation exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::FileError\fP"
.br
.RI "File error abstract base exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::UnknownFileType\fP"
.br
.RI "Unknown file type exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::FileOpenError\fP"
.br
.RI "File open exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::FileContentError\fP"
.br
.RI "File content exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::DestinationError\fP"
.br
.RI "\fBDestination\fP exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::LibraryError\fP"
.br
.RI "Library exception\&. "
.ti -1c
.RI "class \fBPhotoFinish::cmsTypeError\fP"
.br
.ti -1c
.RI "class \fBPhotoFinish::WebPError\fP"
.br
.RI "WebP exception\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
