.TH "JP2.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JP2.hh
.SH SYNOPSIS
.br
.PP
\fC#include <openjpeg\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPhotoFinish::error_callback\fP (const char *msg, void *client_data)"
.br
.RI "Error callback for OpenJPEG - throw a \fBLibraryError\fP exception\&. "
.ti -1c
.RI "void \fBPhotoFinish::warning_callback\fP (const char *msg, void *client_data)"
.br
.RI "Warning callback for OpenJPEG - print the message to STDERR\&. "
.ti -1c
.RI "void \fBPhotoFinish::info_callback\fP (const char *msg, void *client_data)"
.br
.RI "Info callback for OpenJPEG - print the indented message to STDERR\&. "
.ti -1c
.RI "template<typename T > void \fBPhotoFinish::read_planar\fP (unsigned int width, unsigned char channels, opj_image_t *image, T *row, unsigned int y)"
.br
.RI "Read a row of image data from OpenJPEG's planar integer components into an LCMS2-compatible single array\&. "
.ti -1c
.RI "template<typename T > void \fBPhotoFinish::write_planar\fP (unsigned int width, unsigned char channels, T *row, opj_image_t *image, unsigned int y)"
.br
.RI "Read a row of planar pixel data into OpenJPEG's planar components\&. "
.ti -1c
.RI "template<typename T > void \fBPhotoFinish::write_packed\fP (unsigned int width, unsigned char channels, T *row, opj_image_t *image, unsigned int y)"
.br
.RI "Read a row of packed pixel data into OpenJPEG's planar components\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
