.TH "JP2reader.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JP2reader.cc
.SH SYNOPSIS
.br
.PP
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <openjpeg\&.h>\fP
.br
\fC#include <omp\&.h>\fP
.br
\fC#include 'ImageFile\&.hh'\fP
.br
\fC#include 'Exception\&.hh'\fP
.br
\fC#include 'JP2\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
