.TH "JXR_formats.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JXR_formats.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Exception\&.hh'\fP
.br
\fC#include 'JXR\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "const PKPixelFormatGUID & \fBPhotoFinish::jxr_pixel_format\fP (unsigned int n)"
.br
.ti -1c
.RI "\fBCMS::Format\fP \fBPhotoFinish::jxr_cms_format\fP (const PKPixelFormatGUID &g)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "jxr_format_subst \fBPhotoFinish::JXR_format_table\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
