.TH "Kernel1Dvar.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel1Dvar.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <omp\&.h>\fP
.br
\fC#include 'Benchmark\&.hh'\fP
.br
\fC#include 'Kernel1Dvar\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsqr\fP(x)   ((x) * (x))"
.br
.ti -1c
.RI "#define \fBmin\fP(x,  y)   ((x) < (y) ? (x) : (y))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define min(x, y)   ((x) < (y) ? (x) : (y))"

.PP
Definition at line 29 of file Kernel1Dvar\&.cc\&.
.SS "#define sqr(x)   ((x) * (x))"

.PP
Definition at line 28 of file Kernel1Dvar\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
