.TH "Kernel2D.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel2D.hh
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'Image\&.hh'\fP
.br
\fC#include 'Exception\&.hh'\fP
.br
\fC#include 'Definable\&.hh'\fP
.br
\fC#include 'sample\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhotoFinish::Kernel2D\fP"
.br
.RI "Creates and stores coefficients for convolving an image\&. "
.ti -1c
.RI "class \fBPhotoFinish::GaussianSharpen\fP"
.br
.RI "\fBGaussianSharpen\fP kernel\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
