.TH "Kernel1Dvar.hh" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel1Dvar.hh
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include 'Destination_items\&.hh'\fP
.br
\fC#include 'Exception\&.hh'\fP
.br
\fC#include 'Definable\&.hh'\fP
.br
\fC#include 'sample\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPhotoFinish::Kernel1Dvar\fP"
.br
.RI "Creates and stores coefficients for cropping and resizing an image\&. "
.ti -1c
.RI "class \fBPhotoFinish::Lanczos\fP"
.br
.RI "\fBLanczos\fP filter\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
