.TH "PhotoFinish::NoTargets" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::NoTargets \- No targets exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exception\&.hh>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoTargets\fP (const std::string &d)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const std::string \fB_destination\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
No targets exception\&. 
.PP
Definition at line 98 of file Exception\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::NoTargets::NoTargets (const std::string & d)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fId\fP Name of destination that has no targets 
.RE
.PP

.PP
Definition at line 107 of file Exception\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* PhotoFinish::NoTargets::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Definition at line 111 of file Exception\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string PhotoFinish::NoTargets::_destination\fC [protected]\fP"

.PP
Definition at line 100 of file Exception\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
