.TH "PhotoFinish::NoResults" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::NoResults \- No results exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exception\&.hh>\fP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNoResults\fP (const std::string &c, const std::string &m)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const std::string \fB_class\fP"
.br
.ti -1c
.RI "const std::string \fB_method\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
No results exception\&. 
.PP
Definition at line 78 of file Exception\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::NoResults::NoResults (const std::string & c, const std::string & m)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIc\fP Class name 
.br
\fIm\fP Method name 
.RE
.PP

.PP
Definition at line 88 of file Exception\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* PhotoFinish::NoResults::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Definition at line 92 of file Exception\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "const std::string PhotoFinish::NoResults::_class\fC [protected]\fP"

.PP
Definition at line 80 of file Exception\&.hh\&.
.SS "const std::string PhotoFinish::NoResults::_method\fC [protected]\fP"

.PP
Definition at line 80 of file Exception\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
