.TH "PhotoFinish::D_target" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::D_target \- Target parameters for destination\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Destination_items\&.hh>\fP
.PP
Inherited by \fBPhotoFinish::Frame\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBD_target\fP > \fBptr\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBD_target\fP (const std::string &n, double w, double h)"
.br
.RI "A target-specific size (in inches) to override the one in the destination\&. "
.ti -1c
.RI "\fBD_target\fP (const std::string &n)"
.br
.ti -1c
.RI "std::string \fBname\fP (void) const"
.br
.ti -1c
.RI "\fBdefinable\fP< double > \fBwidth\fP (void) const"
.br
.ti -1c
.RI "\fBdefinable\fP< double > \fBheight\fP (void) const"
.br
.ti -1c
.RI "\fBdefinable\fP< double > \fBsize\fP (void) const"
.br
.ti -1c
.RI "void \fBread_config\fP (const YAML::Node &node)"
.br
.RI "Read a \fBD_target\fP record from a YAML file\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fB_name\fP"
.br
.ti -1c
.RI "\fBdefinable\fP< double > \fB_width\fP"
.br
.ti -1c
.RI "\fBdefinable\fP< double > \fB_height\fP"
.br
.ti -1c
.RI "\fBdefinable\fP< double > \fB_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Target parameters for destination\&. 
.PP
Definition at line 84 of file Destination_items\&.hh\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<\fBD_target\fP> \fBPhotoFinish::D_target::ptr\fP"

.PP
Definition at line 101 of file Destination_items\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::D_target::D_target (const std::string & n, double w, double h)"

.PP
A target-specific size (in inches) to override the one in the destination\&. 
.PP
Definition at line 68 of file Destination_items\&.cc\&.
.SS "PhotoFinish::D_target::D_target (const std::string & n)"

.PP
Definition at line 73 of file Destination_items\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBdefinable\fP<double> PhotoFinish::D_target::height (void) const\fC [inline]\fP"

.PP
Definition at line 96 of file Destination_items\&.hh\&.
.SS "std::string PhotoFinish::D_target::name (void) const\fC [inline]\fP"

.PP
Definition at line 94 of file Destination_items\&.hh\&.
.SS "void PhotoFinish::D_target::read_config (const YAML::Node & node)"

.PP
Read a \fBD_target\fP record from a YAML file\&. 
.PP
Definition at line 78 of file Destination_items\&.cc\&.
.SS "\fBdefinable\fP<double> PhotoFinish::D_target::size (void) const\fC [inline]\fP"

.PP
Definition at line 97 of file Destination_items\&.hh\&.
.SS "\fBdefinable\fP<double> PhotoFinish::D_target::width (void) const\fC [inline]\fP"

.PP
Definition at line 95 of file Destination_items\&.hh\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBdefinable\fP<double> PhotoFinish::D_target::_height\fC [protected]\fP"

.PP
Definition at line 87 of file Destination_items\&.hh\&.
.SS "std::string PhotoFinish::D_target::_name\fC [protected]\fP"

.PP
Definition at line 86 of file Destination_items\&.hh\&.
.SS "\fBdefinable\fP<double> PhotoFinish::D_target::_size\fC [protected]\fP"

.PP
Definition at line 88 of file Destination_items\&.hh\&.
.SS "\fBdefinable\fP<double> PhotoFinish::D_target::_width\fC [protected]\fP"

.PP
Definition at line 87 of file Destination_items\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
