.TH "PhotoFinish::CropSolver" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::CropSolver \- Class for finding the best frame position for cropping\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CropSolution\&.hh>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCropSolver\fP (\fBmultihash\fP &vars)"
.br
.ti -1c
.RI "\fBFrame::ptr\fP \fBsolve\fP (\fBImage::ptr\fP img, \fBD_target::ptr\fP target)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class for finding the best frame position for cropping\&. 
.PP
Definition at line 39 of file CropSolution\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::CropSolver::CropSolver (\fBmultihash\fP & vars)"

.PP
Definition at line 47 of file CropSolution\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBFrame::ptr\fP PhotoFinish::CropSolver::solve (\fBImage::ptr\fP img, \fBD_target::ptr\fP target)"

.PP
Definition at line 68 of file CropSolution\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
