.TH "photofinish.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
photofinish.cc
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'Image\&.hh'\fP
.br
\fC#include 'ImageFile\&.hh'\fP
.br
\fC#include 'Destination\&.hh'\fP
.br
\fC#include 'Tags\&.hh'\fP
.br
\fC#include 'Kernel2D\&.hh'\fP
.br
\fC#include 'Exception\&.hh'\fP
.br
\fC#include 'Benchmark\&.hh'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 38 of file photofinish\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
