.TH "PhotoFinish::UnknownFileType" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::UnknownFileType \- Unknown file type exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exception\&.hh>\fP
.PP
Inherits \fBPhotoFinish::FileError\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUnknownFileType\fP (const std::string &fp, const std::string &m)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBUnknownFileType\fP (const std::string &fp)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "virtual const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Unknown file type exception\&. 
.PP
Definition at line 176 of file Exception\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::UnknownFileType::UnknownFileType (const std::string & fp, const std::string & m)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfp\fP File path 
.br
\fIm\fP Error message 
.RE
.PP

.PP
Definition at line 183 of file Exception\&.hh\&.
.SS "PhotoFinish::UnknownFileType::UnknownFileType (const std::string & fp)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfp\fP File path 
.RE
.PP

.PP
Definition at line 191 of file Exception\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* PhotoFinish::UnknownFileType::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBPhotoFinish::FileError\fP\&.
.PP
Definition at line 195 of file Exception\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
