.TH "PhotoFinish::GaussianSharpen" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::GaussianSharpen \- \fBGaussianSharpen\fP kernel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Kernel2D\&.hh>\fP
.PP
Inherits \fBPhotoFinish::Kernel2D\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGaussianSharpen\fP ()"
.br
.RI "Empty constructor\&. "
.ti -1c
.RI "\fBGaussianSharpen\fP (const \fBD_sharpen\fP &ds)"
.br
.RI "Constructor\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBGaussianSharpen\fP kernel\&. 
.PP
Definition at line 76 of file Kernel2D\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::GaussianSharpen::GaussianSharpen ()"

.PP
Empty constructor\&. 
.PP
Definition at line 262 of file Kernel2D\&.cc\&.
.SS "PhotoFinish::GaussianSharpen::GaussianSharpen (const \fBD_sharpen\fP & ds)"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIds\fP A \fBD_sharpen\fP object which will supply our parameters\&. 
.RE
.PP

.PP
Definition at line 265 of file Kernel2D\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
