.TH "PhotoFinish::jpeg_destination_state_t" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::jpeg_destination_state_t \- Structure holding information for the ostream writer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "JOCTET * \fBbuffer\fP"
.br
.ti -1c
.RI "std::ostream * \fBos\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure holding information for the ostream writer\&. 
.PP
Definition at line 106 of file JPEG_iostream\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "JOCTET* PhotoFinish::jpeg_destination_state_t::buffer"

.PP
Definition at line 107 of file JPEG_iostream\&.cc\&.
.SS "size_t PhotoFinish::jpeg_destination_state_t::buffer_size"

.PP
Definition at line 109 of file JPEG_iostream\&.cc\&.
.SS "std::ostream* PhotoFinish::jpeg_destination_state_t::os"

.PP
Definition at line 108 of file JPEG_iostream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
