.TH "PhotoFinish::jpeg_source_state_t" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::jpeg_source_state_t \- Structure holding information for the istream reader\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "JOCTET * \fBbuffer\fP"
.br
.ti -1c
.RI "std::istream * \fBis\fP"
.br
.ti -1c
.RI "size_t \fBbuffer_size\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Structure holding information for the istream reader\&. 
.PP
Definition at line 27 of file JPEG_iostream\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "JOCTET* PhotoFinish::jpeg_source_state_t::buffer"

.PP
Definition at line 28 of file JPEG_iostream\&.cc\&.
.SS "size_t PhotoFinish::jpeg_source_state_t::buffer_size"

.PP
Definition at line 30 of file JPEG_iostream\&.cc\&.
.SS "std::istream* PhotoFinish::jpeg_source_state_t::is"

.PP
Definition at line 29 of file JPEG_iostream\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
