.TH "PhotoFinish::MemAllocError" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhotoFinish::MemAllocError \- Memory allocation exception\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exception\&.hh>\fP
.PP
Inherits \fBPhotoFinish::ErrorMsg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemAllocError\fP (const std::string &m)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "const char * \fBwhat\fP () const noexcept"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Memory allocation exception\&. 
.PP
Definition at line 134 of file Exception\&.hh\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhotoFinish::MemAllocError::MemAllocError (const std::string & m)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIm\fP Error message 
.RE
.PP

.PP
Definition at line 140 of file Exception\&.hh\&.
.SH "Member Function Documentation"
.PP 
.SS "const char* PhotoFinish::MemAllocError::what () const\fC [inline]\fP, \fC [virtual]\fP, \fC [noexcept]\fP"

.PP
Implements \fBPhotoFinish::ErrorMsg\fP\&.
.PP
Definition at line 144 of file Exception\&.hh\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
