.TH "SOLwriter.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SOLwriter.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'ImageFile\&.hh'\fP
.br
\fC#include 'Image\&.hh'\fP
.br
\fC#include 'Ditherer\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBPhotoFinish::write_be\fP (void *ptr, size_t size, std::ostream &stream)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned char \fBPhotoFinish::header\fP [12]"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
