.TH "Tags_IPTC_subst.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tags_IPTC_subst.cc
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <map>\fP
.br
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include 'Tags\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "Exiv2::IptcKey \fBPhotoFinish::iptc_key_read\fP (std::string key_string)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "subst_table \fBPhotoFinish::IPTC_key_subst\fP"
.br
.RI "Map from Image::Exiftool tag names to Exiv2's tag names\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
