.TH "WebPwriter.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebPwriter.cc
.SH SYNOPSIS
.br
.PP
\fC#include <boost/algorithm/string\&.hpp>\fP
.br
\fC#include <webp/encode\&.h>\fP
.br
\fC#include <omp\&.h>\fP
.br
\fC#include 'ImageFile\&.hh'\fP
.br
\fC#include 'Exception\&.hh'\fP
.br
\fC#include 'WebP_ostream\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::map< std::string, WebPPreset > \fBPhotoFinish::WebP_presets\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
