.TH "WebP_ostream.cc" 3 "Mon Mar 6 2017" "Version 1" "Photo Finish" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WebP_ostream.cc
.SH SYNOPSIS
.br
.PP
\fC#include <webp/encode\&.h>\fP
.br
\fC#include 'WebP_ostream\&.hh'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPhotoFinish\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBmin\fP(a,  b)   ((a) < (b) ? (a) : (b))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBPhotoFinish::webp_stream_writer_func\fP (const uint8_t *data, size_t data_size, const WebPPicture *picture)"
.br
.RI "Wrapper around the \fBwebp_stream_writer\fP class\&. "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define min(a, b)   ((a) < (b) ? (a) : (b))"

.PP
Definition at line 133 of file WebP_ostream\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Photo Finish from the source code\&.
